### ISSUE TITLE
Create beat to ship Kafka consumer health stats

### ISSUE THREAD

**Issue by towens-goomzee** [Goomzee/burrowbeat#1]
Please create a beat that ships Kafka consumer health stats to Elastic Search for visualization. Data sent from the beat should be delivered in the format below:

~~~
{
    "beat": {
        "name": "burrowbeat",
        "host": "localhost"
    },
    "@timestamp": "YYYY-MM-DDTHH:MM:SS.milliZ",
    "@version": "1",
    "type": "kafkastat",
    "count": 1,
    "consumer_group_name": "someval", 
    "lag": 0, 
    "offset": 0
}
~~~

**Comment by monicasarbu** [comment]
There is a community Beat, [Kafkabeat](https://github.com/gingerwizard/kafkabeat), that can help you here.

**Comment by mikesparr** [comment]
Thanks @monicasarbu - we are familiar with Kafkabeat and I submitted a pull request to fix some of their old code that doesn't work with newer Go or Beats library and it hasn't been updated. Burrow beat takes advantage of Burrow which solves some limitations in lag checking in Kafka itself. ;-) See: https://github.com/linkedin/Burrow/wiki/What-is-Burrow

**Comment by ruflin** [comment]
@mikesparr Very interesting. We are currently working on adding more modules to metricbeat: https://github.com/elastic/beats/tree/master/metricbeat Kafka and Cassandra are both on our list to be added. Perhaps we could do some collaboration here?
